---
title: Curriculum Vitae - Hannah Redmond - Lead Front End Developer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://hmredmond.github.io
baseurl: "/cv"
profile-name: Hannah Redmond
style: aqua
name: Hannah Redmond
tagline: Lead Front End Developer
pic: profile.png
summary: 'Highly motivated and enthusiastic lead front end developer with 15 years’
  commercial experience working in the fast paced world of software and web development.
  Principal skills offered include excellent front end development and full stack
  knowledge combined with technical proficiency and proven abilities in communication,
  teamwork and time management. '
email: hmredmond@hotmail.com
phone: '07976713110'
website: 
linkedin: hannah-redmond-4511251
github: hmredmond
twitter: "@hmredmond"
cv: hannah_redmond_fed_cv.doc
analytics: 
encoding: utf-8
compress_html:
  clippings: all
  ignore:
    envs: development
