---
upload_path: "/assets/files"
frontmatter_file_url_template: "/uploads/fem"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
