name: Copy README to Docs

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pandoc
        run: |
          sudo apt-get -y install pandoc  # Install pandoc on Ubuntu
          # Add commands to install pandoc for other operating systems if needed

      - name: Copy README to docs folder
        run: |
          pandoc -s README.md -o docs/README.md

      - name: Copy LICENCE to docs folder
        run: |
          pandoc -s LICENCE.md -o docs/LICENCE.md
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "Update docs folder with README"
          git push
