name: Copy Documents For Backstage

on: push

jobs:
  copy_do_docs_folder:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            README.md
            -o ./docs/readme.md
